// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flzeosorsximpohcnvxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsemVvc29yc3hpbXBvaGNudnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzE5ODIsImV4cCI6MjA2OTAwNzk4Mn0.I8Ap_4kg3Sn8maBoIV_qrBhOh28YvWr_rzsXS5Rn07g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});